# Generated by Django 5.0 on 2023-12-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_Number", models.CharField(max_length=50)),
                ("occupied", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=15)),
                ("patient_relative_name", models.CharField(max_length=50, null=True)),
                (
                    "patient_relative_contact",
                    models.CharField(max_length=15, null=True),
                ),
                ("address", models.TextField()),
                ("prior_ailnments", models.TextField()),
                ("dob", models.DateField(null=True)),
                ("doctors_notes", models.TextField(blank=True, null=True)),
                (
                    "doctors_visiting_time",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("status", models.CharField(max_length=50)),
                (
                    "bed_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.bed"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.doctor",
                    ),
                ),
            ],
        ),
    ]
