# Generated by Django 5.0 on 2023-12-22 14:39

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="symptoms",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
