# Generated by Django 3.1.6 on 2023-12-22 14:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_patient_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fever', 'Fever'), ('Dry cough', 'Dry cough'), ('Tiredness', 'Tiredness'), ('Aches and pains', 'Aches and pains'), ('Sore throat', 'Sore throat'), ('Diarrhoea', 'Diarrhoea')], max_length=63, null=True),
        ),
    ]
