# Generated by Django 3.1.6 on 2023-12-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20231222_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.CharField(default='Ward-0', max_length=50),
        ),
    ]
