# Generated by Django 3.1.6 on 2024-01-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20240110_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prior_ailnments',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
    ]
